import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ProfileHeader from "./components/header/ProfileHeader"
import Sidebar from "./components/sidebar/Sidebar";
import AboutUser from "./components/sections/aboutUser/AboutUser"
import WorkExperience from "./components/sections/workExperience/WorkExperience"
import Education from "./components/sections/education/Education"
import AwardsAndCertifications from "./components/sections/awardsAndCertifications/AwardsAndCertifications"
import FeaturedVideos from "./components/sections/featuredVideos/FeaturedVideos"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      > 
        <ProfileHeader />
        <div className="flex items-stretch justify-between  min-h-screen" >
          <Sidebar />
          <main className="flex flex-col items-center justify-between gap-5 py-5">
            <AboutUser />
            <WorkExperience />
            <Education />
            <AwardsAndCertifications />
            <FeaturedVideos />
          </main>
        </div>
        {children}
      </body>
    </html>
  );
}
